name: Publish
on:
  push:
    tags: v*.*.*
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Poetry 2.1.0
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.2
    - name: Run tests
      run: make tests
    - name: Run build
      run: poetry build
    - name: Publish in GitHub Releases
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    # - name: Publish in PyPI
    #   uses: d1618033/gh-action-python-publish-using-poetry@master
    #   with:
    #     pypi_username: ${{ secrets.PYPI_USERNAME }}
    #     pypi_password: ${{ secrets.PYPI_PASSWORD }}
